version: "2"
services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Mack0319
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
  app:
    build: ./app
    ports:
      - "2000:80"
    restart: on-failure:10
    links: 
      - db
    depends_on:
      - db   
